name: LOS 17.1 onclite

on:
#  repository_dispatch:
  workflow_dispatch:
#  push:
#  release:
#    types: [released, edited]

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Build
        run: |
         su <<EOSU
         apt update && apt install --no-install-recommends -qy bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-11-jdk repo brotli unzip
         mkdir -p ~/bin
         mkdir -p ~/android/lineage
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
         chmod a+x ~/bin/repo
         echo "# set PATH so it includes user's private bin if it exists
         if [ -d "$HOME/bin" ] ; then
             PATH="$HOME/bin:$PATH"
         fi" >> ~/.profile
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         source ~/.profile
         cd ~/android/lineage
         ln -s /usr/bin/python3 /usr/bin/python
         repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
         repo sync -c -j`nproc`
         source build/envsetup.sh
         breakfast onclite
         mkdir ~/android/system_dump/
         cd ~/android/system_dump/
         wget https://b2.timschumi.net/file/lineage-archive/lineage-17.1-20210214-nightly-onclite-signed.zip
         unzip lineage-*.zip system.transfer.list system.new.dat*
         unzip lineage-*.zip vendor.transfer.list vendor.new.dat*
         brotli --decompress --output=system.new.dat system.new.dat.br
         brotli --decompress --output=vendor.new.dat vendor.new.dat.br
         git clone https://github.com/xpirt/sdat2img
         python3 sdat2img/sdat2img.py system.transfer.list system.new.dat system.img
         mkdir system/
         mount system.img system/
         python3 sdat2img/sdat2img.py vendor.transfer.list vendor.new.dat vendor.img
         rm -rf system/vendor
         mkdir system/vendor
         mount vendor.img system/vendor/
         cd ~/android/lineage/device/xiaomi/onclite
         ./extract-files.sh ~/android/system_dump/
         croot
         brunch onclite
         cd $OUT
         mv *.zip *.img ${GITHUB_WORKSPACE}/releases
         EOSU
      - name: Move bins to release dir
        run: |
          mv *.deb ${GITHUB_WORKSPACE}/releases
      - name: Generate release tag
        run: |
          echo "::set-output name=release_tag::17.1"
          touch release.txt
          echo "Last updated on $(date +"%Y.%m.%d-%H:%M") UTC+08:00" >> release.txt
      - name: Upload bins to release
        uses: softprops/action-gh-release@v1
        with:
         tag_name: 17.1
         body_path: release.txt
         files: releases/*
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
         retain_days: 1
         keep_minimum_runs: 3
         
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Clean
      run: |
        rm -rf release bbr
    - name: Commit
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan new_branch
        git add -A
        git commit -am "update new file"
        git branch -D main
        git branch -m main
        git push origin main --force
